# Generated by Django 4.1.1 on 2022-09-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='booksapi_bo_price_45c189_idx',
            old_name='booksapi_bo_price_2ccb76_idx',
        ),
    ]
